### PR TITLE
Created a pull request template file.

### PR DESCRIPTION
**Pull request by primis**
If merged it will enable github pull requests to have it when you attempt to submit one.

### CODE REVIEW

**Comment by primis** [comment]
I added the Template File.
Resolves #50 

- [x] checkbox for posterity :+1:

**Comment by pimterry** [comment]
Looks good to me! Merged.

As an aside - would you like to be a co-maintainer on this repo? It's great to see you putting so much energy into it, and I don't really have enough time to be as responsive as I'd like for a lot of things here alone. That way you can do releases and small changes for yourself, and I'm happy to be around for reviews etc where I can, but when I can't be you're free to keep things moving however you'd like. How does that sound?

**Comment by primis** [comment]
I'd be happy to!

**Comment by pimterry** [comment]
Great, done! :smiley:

I don't think we need much structure around this, but the one bit you might not have seen is the release process. To ship a new release it's just:

* Tag the commit with the new version (following [semver](semver.org)) & push it
* Add a release in github releases for the tag with some quite notes about the contents
* Update the `latest-release` branch, which is the version the installer uses

**Pull request merged**
