### PR TITLE
New command: `realpath`

### LINKED ISSUE #92: Notes open does not cd to notes directory
#### Issue Summary

The documentation as well as the `--help` command specify that using `notes open|o` would open my notes directory. But it does not. 

#### Steps to Reproduce

1. Install notes
2. Specify your notes directory
3. Enter `notes o`

After these steps, this is the output of the script: `/usr/local/bin/notes: line 232: open: command not found`

#### Technical details:

* notes version: 1.3.0

### LINKED ISSUE #93: Pass args to Post install script
#### Issue Summary

Post Script passes no information to the script. I write my notes in `md` files and I would like to write a script that uses `pandoc` to convert the md to pdf files when the `vim` process completes. However, no information is passed to the post-script to make use of a script.

#### Technical details:

* notes version: master (latest commit: [commit number])

### PR DESCRIPTION
**Pull request by cybercoder-naj**
# Resolves #93 
# Closes #92 

### Checklist
- [x] I have made a change to this repository, be it functionality, testing, documentation, spelling, or grammar.
- [x] I updated my branch with the master branch.
- [x] I have added the necessary testing to prove my fix is effective/my feature works (or I did not modify functionality).
- [x] I have added necessary documentation about the functionality in an appropriate .md file.
- [x] I have appropriately commented any code I have modified

### Short description of what this PR does:
- A new command `realpath` is added to echo the path to the a note by the name provided. 
- If no note was provided, `realpath` would echo `$NOTES_DIRECTORY`.
- If a note which does not exist was provided, `realpath` would echo the future path to that file.
- As a consequence, A user can run `cd "$(notes realpath)"` to `cd` into `$NOTES_DIRECTORY`.

### CODE REVIEW

**Comment by cybercoder-naj** [comment]
I have an issue by running a particular test case. If you have have a look at my test case [here](https://github.com/pimterry/notes/pull/94/files#diff-b0d1f38904643fdac5043e933ab21b21a0525e40851dab1cd580679a42cd8d6cR29-R35), it runs indefinitely. Funny enough, a Ctrl+C (SIGINT) does not stop the test case; force quitting the terminal is the only option. However, the other test cases work. Can someone please guide why this error occurs and how to fix it?

**Review by pimterry — CHANGES_REQUESTED** [review]
> I have an issue by running a particular test case. If you have have a look at my test case [here](https://github.com/pimterry/notes/pull/94/files#diff-b0d1f38904643fdac5043e933ab21b21a0525e40851dab1cd580679a42cd8d6cR29-R35), it runs indefinitely.

You're not overriding `EDITOR` anywhere in the test case, so the `notes new` in that test is actually opening up your real editor somewhere, and blocking while until that exits.

You can use something like `export EDITOR=touch` to skip that, as in some of the other similar tests.

I think that's the only changed required here though, otherwise this all looks good to me! Very clean. If you patch that up and check it works, I'll merge this :+1:

**Comment by cybercoder-naj** [comment]
> > I have an issue by running a particular test case. If you have have a look at my test case [here](https://github.com/pimterry/notes/pull/94/files#diff-b0d1f38904643fdac5043e933ab21b21a0525e40851dab1cd580679a42cd8d6cR29-R35), it runs indefinitely.
> 
> You're not overriding `EDITOR` anywhere in the test case, so the `notes new` in that test is actually opening up your real editor somewhere, and blocking while until that exits.
> 
> You can use something like `export EDITOR=touch` to skip that, as in some of the other similar tests.
> 
> I think that's the only changed required here though, otherwise this all looks good to me! Very clean. If you patch that up and check it works, I'll merge this 👍

Thanks for your help. The test cases pass successfully now.

**Review by pimterry — APPROVED** [review]

**Comment by pimterry** [comment]
Perfect, thanks! :+1:

**Pull request merged**
