### PR TITLE
exit 1  on failure to create NOTES_DIRECTORY

### LINKED ISSUE #55: exits successfully($? is 0) when it fails to create notes
#### Issue Summary
When `$NOTES_DIRECTORY` is set to a *filename*, that already exists in the directory.
It opens a new note but fails to save it, and exits 0
(as the exit status depends on the editor)

#### Steps to Reproduce

1. touch /tmp/secret
2. env NOTES_DIRECTORY=/tmp/secret notes n leaks
3. edit and save(fails to save), quit forcefully.
4.  Once you are back at shell, `echo $?`

#### Expected Behavior
exit before opening the editor and ask user to set `NOTES_DIRECTORY` to a safe location.
ofc, exit with non-zero status

### PR DESCRIPTION
**Pull request by rmNULL**
# Fixes # 
Fixes #55 
Closes #55 

### Checklist
- [x] I have made a change to this repository, be it functionality, testing, documentation, spelling, or grammar.
- [x] I updated my branch with the master branch.
- [ ] I have added the necessary testing to prove my fix is effective or my feature work, or I did not modify functionality.
- [ ] I have added necessary documentation about the functionality in an appropriate .md file
- [x] I have commented any code I have modified or I did not modify any code

### Short description of what this PR does:
- When `mkdir` fails create NOTES_DIRECTORY, it exits with 
an error message to user

### CODE REVIEW

**Comment by primis** [comment]
It looks great, but I might suggest adding a "please" to the change to sound nicer. Or an explanation like "Could not create the notes directory, please change..." for verbosity sake.

**Comment by rmNULL** [comment]
okay, sure.

**Comment by pimterry** [comment]
I've added a couple of bonus tweaks to this (and tests), but overall it looks great to me! Merging now.

**Comment by rmNULL** [comment]
Lol nice. "Could not create directory " will be redundant output as `mkdir` 
outputs a similar message. Maybe we should redirect `mkdir` to /dev/null

**Pull request merged**
