### PR TITLE
Add combined grep/find as search

### PR DESCRIPTION
**Pull request by khamer**
Here's a rough implementation of a combining grep/find together, so that you can search for files based on filename or contents. Performance might be better if we ran the grep and find separately and then sorted/uniq'd the results together, but this solution works.

I did run the tests and threw together a new test-search.bats based on the others. I called this functionality 'search' as I wasn't sure whether you wanted this to replace existing functionality or not.

### CODE REVIEW

**Review by pimterry — CHANGES_REQUESTED** [review]
This need documenting in the README, and rebasing. Otherwise it this looks good to me though.

In future I would like to move this to an implementation that calls find & grep under the hood and combines the results, just because that seems quite elegant, but the outward facing behaviour should be the same, so I'm happy to start with this.

**Comment by khamer** [comment]
I've updated the README.

**Comment by khamer** [comment]
README updated and rebased PR into a single commit.

**Comment by pimterry** [comment]
README looks good, but the build's now broken - looks like there's a syntax error somewhere.

**Comment by khamer** [comment]
Just pushed some changes that should getting it passing the tests; sorry about that.

**Comment by pimterry** [comment]
Looks good, thanks! Merged.

**Pull request merged**
