### PR TITLE
Added ability to override config with CLI options

### PR DESCRIPTION
**Pull request by apatil**
Adds ability to override config with CLI options.

I haven't added tests or updated the man page yet. I wanted to check first whether you'd be interested in this change.

### Checklist
- [x] I have made a change to this repository, be it functionality, testing, documentation, spelling, or grammar.
- [x] I updated my branch with the master branch.
- [ ] I have added the necessary testing to prove my fix is effective/my feature works (or I did not modify functionality).
- [ ] I have added necessary documentation about the functionality in an appropriate .md file.
- [ ] I have appropriately commented any code I have modified

### CODE REVIEW

**Comment by pimterry** [comment]
Hmm, sorry, I'm not totally convinced by this.

I can just about see cases where you might want this, but I'm not clear why `notes --editor myeditor new` is better than `EDITOR=myeditor notes new`. The latter already works, doesn't require any separate logic, and using env vars only feels a bit simpler conceptually that having two different sources of configuration.

What do you think? Is there a reason that doesn't work?

**Comment by apatil** [comment]
The issue is that the config file always overrides environmental variables, and both are always read by the script. I want to put most of my notes in one folder but some notes in another folder.

**Comment by primis** [comment]
Since the config is a bash file itself, you could easily put a test in the config like so:
```bash
if [ -z "$EDITOR" ]
then
   EDITOR=nano
fi
```

This would allow an override such as @pimterry had suggested.
Closing pull request as duplicate functionality.

**Comment by apatil** [comment]
What if I sometimes want NOTES_DIR to be /keybase/private/me/notes and sometimes /keybase/teams/someteam/notes? It's cumbersome to keep editing the config file just to put notes in another folder.

**Comment by primis** [comment]
In your config:
```bash
if [  -z "$NOTES_DIR" ]
then
    NOTES_DIR=<PRIMARY>
fi
```

And if you wanna use a different directory, run notes like:
`NOTES_DIR=<Directory> notes ...`

**Comment by apatil** [comment]
Ah, I see. That works.

**Pull request closed without merging**
